export const SEND_TEXT_MESSAGE_SUCCEEDED = 'SEND_TEXT_MESSAGE_SUCCEEDED'
export const SEND_TEXT_MESSAGE_FAILED = 'SEND_TEXT_MESSAGE_FAILED'
export const SEND_TEXT_MESSAGE_REQUESTED = 'SEND_TEXT_MESSAGE_REQUESTED'

export const BASE_URL = 'https://rest.nexmo.com/sms/json'
